version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: game-integration-api
    ports:
      - "3000:3000"
    env_file: ".env"
    depends_on:
      - postgres
    volumes:
      - .:/app
    restart: unless-stopped

  postgres:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Optional: for initial DB setup
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3

  wallet-client:
    image: kentechsp/wallet-client
    container_name: wallet-client-backend
    ports:
      - "8080:8080"  # Adjust port as needed
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
