// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "API Support",
            "email": "support@gameintegration.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/auth": {
            "post": {
                "description": "Authenticates a player using username and password, returns a JWT token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Authenticate player",
                "parameters": [
                    {
                        "description": "Authentication credentials",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.AuthRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Authentication successful",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/shared.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/shared.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/cancel": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Reverts a previously processed transaction by reversing its financial impact",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Betting"
                ],
                "summary": "Cancel a transaction",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer \u003ctoken\u003e",
                        "description": "Bearer token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Cancel request details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/shared.CancelRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Transaction cancelled successfully",
                        "schema": {
                            "$ref": "#/definitions/shared.BetOperationResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/shared.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/shared.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Transaction not found",
                        "schema": {
                            "$ref": "#/definitions/shared.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/shared.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/deposit": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Processes a deposit into a player's account. Represents bet settlement - if amount is zero, bet is LOST; otherwise, bet is WON.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Betting"
                ],
                "summary": "Settle a bet",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer \u003ctoken\u003e",
                        "description": "Bearer token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Settle request details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/shared.DepositRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Bet settled successfully",
                        "schema": {
                            "$ref": "#/definitions/shared.BetOperationResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/shared.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/shared.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/shared.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/player-info": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieves essential player details including user ID, balance, and currency",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Player"
                ],
                "summary": "Get player information",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer \u003ctoken\u003e",
                        "description": "Bearer token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Player information",
                        "schema": {
                            "$ref": "#/definitions/shared.PlayerInfoResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/shared.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/shared.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/withdraw": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Processes a withdrawal from a player's balance. Each request represents a bet placement action.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Betting"
                ],
                "summary": "Process a bet",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer \u003ctoken\u003e",
                        "description": "Bearer token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Bet request details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/shared.WithdrawRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Bet processed successfully",
                        "schema": {
                            "$ref": "#/definitions/shared.BetOperationResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/shared.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/shared.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/shared.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.Currency": {
            "type": "string",
            "enum": [
                "USD",
                "EUR",
                "KES"
            ],
            "x-enum-varnames": [
                "CurrencyUSD",
                "CurrencyEUR",
                "CurrencyKES"
            ]
        },
        "models.TransactionStatus": {
            "type": "string",
            "enum": [
                "PENDING",
                "CONFIRMED",
                "FAILED",
                "FINAL",
                "PROCESSING"
            ],
            "x-enum-varnames": [
                "TransactionStatusPending",
                "TransactionStatusConfirmed",
                "TransactionStatusFailed",
                "TransactionStatusFinalized",
                "TransactionStatusProcessing"
            ]
        },
        "service.AuthRequest": {
            "type": "object",
            "properties": {
                "password": {
                    "type": "string",
                    "example": "demo123!"
                },
                "username": {
                    "type": "string",
                    "example": "player_34633089486"
                }
            }
        },
        "shared.BetOperationResponse": {
            "type": "object",
            "properties": {
                "new_balance": {
                    "type": "string",
                    "example": "1000.50"
                },
                "old_balance": {
                    "type": "string",
                    "example": "1900.50"
                },
                "provider_transaction_id": {
                    "type": "integer",
                    "example": 12345
                },
                "status": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.TransactionStatus"
                        }
                    ],
                    "example": "CONFIRMED"
                },
                "transaction_id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                }
            }
        },
        "shared.CancelRequest": {
            "type": "object",
            "required": [
                "provider_transaction_id"
            ],
            "properties": {
                "provider_transaction_id": {
                    "type": "integer",
                    "example": 12345
                }
            }
        },
        "shared.DepositRequest": {
            "type": "object",
            "required": [
                "currency",
                "provider_transaction_id",
                "provider_withdrawn_transaction_id"
            ],
            "properties": {
                "amount": {
                    "type": "number",
                    "minimum": 0,
                    "example": 1000
                },
                "currency": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.Currency"
                        }
                    ],
                    "example": "USD"
                },
                "provider_transaction_id": {
                    "type": "integer",
                    "example": 12345
                },
                "provider_withdrawn_transaction_id": {
                    "type": "integer",
                    "example": 12344
                }
            }
        },
        "shared.ErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/shared.errorCode"
                        }
                    ],
                    "example": "Invalid request"
                },
                "msg": {
                    "type": "string",
                    "example": "Validation failed"
                }
            }
        },
        "shared.PlayerInfoResponse": {
            "type": "object",
            "properties": {
                "balance": {
                    "type": "string",
                    "example": "1000.50"
                },
                "currency": {
                    "type": "string",
                    "example": "USD"
                },
                "user_id": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "shared.WithdrawRequest": {
            "type": "object",
            "required": [
                "amount",
                "currency",
                "provider_transaction_id"
            ],
            "properties": {
                "amount": {
                    "type": "number",
                    "example": 100
                },
                "currency": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.Currency"
                        }
                    ],
                    "example": "USD"
                },
                "provider_transaction_id": {
                    "type": "integer",
                    "example": 12345
                }
            }
        },
        "shared.errorCode": {
            "type": "string",
            "enum": [
                "REQUEST_VALIDATION_ERROR",
                "SERVICE_UNAVAILABLE",
                "INTERNAL_SERVER_ERROR",
                "UNAUTHORIZED"
            ],
            "x-enum-varnames": [
                "ValidationError",
                "ServiceUnAvailable",
                "InternalServerError",
                "Unauthorized"
            ]
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Type \"Bearer\" followed by a space and JWT token.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:3000",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Game Integration API",
	Description:      "Game Integration API for managing players, bets, and transactions",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
